image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

pages:
  script:
  - node script/build
  - mkdir -p public/v2
  - mv build public/v2
  
  artifacts:
    paths:
    - public